spring:
  application:
    name: everyWeb
  datasource:
    url: jdbc:postgresql://localhost:5433/everyWeb
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  task:
    scheduling:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2MB
      location: ./tmp
app:
  wallpaper:
    upload-dir: ./wallpapers
    max-file-size: 52428800    # 50MB
    allowed-extensions: jpg,jpeg,png,gif,bmp,webp
  push:
    public-key: "BBWEgedaobNc5WjJzkW95dMFudVyt5HlM0p_423KIbGXFwaiCmT8IT8GgUubTxtsiKj2nttJWm46yjLBT_pWv1g"
    private-key: "c7Z-P77-8onldW9_1m_PspkgRGNIH30w-pjj8Nlb6CM"
    fcm-server-key: "BOmFCOFnvK-zlR2N1PfZFPafnfVXk8EMTCozZel4x0NyTfvdeG0PuOfWE5Y1zt-53cd-6AhoeMQ2BRJBztsBBsE"
    fcm-project-id: "everyweb-71176"